### ISSUE TITLE
Web-page todo

### ISSUE THREAD

**Issue by Xanonymous-GitHub** [NPC-GO/hey-ptt#2]
- [x] 改為直接出現「最新列表」而不是無意義首頁

- [x] 部署到GCP掛SSL

- [x] 頁面有夠醜，盡量美化點

- [x] 異步處理時，要有等待動畫，例如，轉轉轉

- [x] 拔除bootstrap(?

- [x] article頁面在手機版會漂浮不定

- [x] article頁面顯示時會當

- [x] article頁面手機如果橫著看標題會過大

- [x] article頁面醜

- [x] ICON
- [x] 內文標題的 margin 增加

- [x] 底部太窄

- [x] article box 事件冒泡

- [x] 支援所有ptt版

- [x] article 標題分隔線未全滿

**Comment by Xanonymous-GitHub** [comment]
finally finish deploy
